os:
    - linux
language: generic
sudo: required
dist: trusty
env:
    - SWIFT_VERSION=4.2
    - SWIFT_VERSION=5.0
    - SWIFT_VERSION=5.1
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
matrix:
    include:
        - os: osx
          osx_image: xcode10
          env: SWIFT_VERSION=4.2
        - os: osx
          osx_image: xcode10
          env: SWIFT_VERSION=5.0
        - os: osx
          osx_image: xcode11
          env: SWIFT_VERSION=5.1
script:
    - swift test
