os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
env:
    - SWIFT_VERSION=3.0.2
    - SWIFT_VERSION=3.1.1
    - SWIFT_VERSION=4.0
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test
