os:
    - linux
language: generic
sudo: required
dist: trusty
matrix:
    include:
        - os: osx
          osx_image: xcode8
          env: SWIFT_VERSION=3.1.1
        - os: osx
          osx_image: xcode9
          env: SWIFT_VERSION=4.0
env:
    - SWIFT_VERSION=3.1.1
    - SWIFT_VERSION=4.0
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test
